const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Flash,
		C3.Behaviors.Follow,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Follow.Acts.FollowSelf,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{ДвижениеК: 0},
	{Мигание: 0},
	{Спрайт: 0},
	{СледоватьЗа: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{Тач: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Flux_Schnell_A_thick_long_arm_wearing_a_luxurious_fur_coat_sle_2Copy: 0},
	{Текст: 0},
	{oDHDR2B4WdM: 0},
	{c5_720x: 0},
	{drTOIydeTs: 0},
	{i4Copy: 0},
	{i3Copy: 0},
	{Частицы: 0},
	{money: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Flux_Schnell_A_thick_long_arm_wearing_a_luxurious_fur_coat_sle_2Copy: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	oDHDR2B4WdM: class extends self.ISpriteInstance {},
	c5_720x: class extends self.ISpriteInstance {},
	drTOIydeTs: class extends self.ISpriteInstance {},
	i4Copy: class extends self.ISpriteInstance {},
	i3Copy: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {}
}